[build]
builder = "dockerfile"
dockerfilePath = "./backend/Dockerfile"
buildContext = "."

[deploy]
startCommand = "java -jar -Dspring.profiles.active=prod target/*.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
